org: carlbarace
app: test-api
service: aws-node-rest-api-project

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  memorySize: 512

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
